const Books = {
  SelfHelp : [
    "The 7 Habits of Highly Effective People",
    "Think and Grow Rich",
    "The Power of Now",
    "Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead",
    "The Miracle Morning",
    "The Alchemist",
    "Mindset: The New Psychology of Success",
    "The 5 AM Club",
    "Essentialism: The Disciplined Pursuit of Less",
    "Deep Work",
    "The One Thing",
    "Atomic Habits",
    "The 10X Rule",
    "The 4-Hour Work Week",
    "The Power of Your Subconscious Mind",
    "The Art of Possibility",
    "The 5 Love Languages",
    "Drive: The Surprising Truth About What Motivates Us",
    "The Happiness Project",
    "Mindfulness: A Practical Guide to Finding Peace in a Frantic World",
    "The How of Happiness",
    "Flow: The Psychology of Optimal Experience",
    "The 7 Spiritual Laws of Success",
    "The Untethered Soul",
    "The Gifts of Imperfection",
    "Presence: Bringing Your Boldest Self to Your Biggest Challenges",
    "The Confidence Gap",
    "The Self-Care Revolution",
    "The Multi-Hyphen Method",
    "You Are a Badass",
    "The Universe Has Your Back",
    "May Cause Miracles",
    "The Vortex",
    "Ask and It is Given",
    "The Power of Intention",
    "The Spontaneous Fulfillment of Desire",
    "The Art of Living",
    "Meditations",
    "The Daily Stoic",
    "Ego Is the Enemy",
    "The Obstacle Is the Way",
    "Stillness Is the Key",
    "Indistractable",
    "Can't Hurt Me",
    "Unshakeable",
    "Money: Master the Game",
    "The Path Made Clear",
    "The Wisdom of Sundays",
    "What I Know for Sure",
    "The Year of Magical Thinking",
    "Wild: From Lost to Found on the Pacific Crest Trail",
    "Man's Search for Meaning",
    "The Power of Vulnerability",
    "The Art of Resilience",
    "The Happiness Advantage",
    "Before Happiness",
    "Rising Strong",
    "Daring to Lead",
    "The Self-Care Revolution",
    "The Mindful Way Workbook",
    "Wherever You Go, There You Are",
    "A New Earth",
    "The Power of Now",
    "The Miracle of Mindfulness",
    "The Art of Happiness",
    "The Dalai Lama's Little Book of Inner Peace",
    "The Book of Awakening",
    "The Wisdom of Insecurity",
    "The Art of Possibility",
    "The 5 AM Club",
    "Essentialism: The Disciplined Pursuit of Less",
    "Deep Work",
    "The One Thing",
    "Atomic Habits",
    "The 10X Rule",
    "The 4-Hour Work Week",
    "The Power of Your Subconscious Mind",
    "The Art of Possibility",
    "The 5 Love Languages",
    "Drive: The Surprising Truth About What Motivates Us",
    "The Happiness Project",
    "Mindfulness: A Practical Guide to Finding Peace in a Frantic World"
  ],
  Health :  [
    "The China Study by T. Colin Campbell and Thomas M. Campbell II",
    "How Not to Die by Michael Greger and Gene Stone",
    "The Blue Zones Solution by Dan Buettner",
    "Food Rules: An Eater's Manual by Michael Pollan",
    "The Omnivore's Dilemma by Michael Pollan",
    "In Defense of Food by Michael Pollan",
    "The Whole30 by Melissa Hartwig and Dallas Hartwig",
    "The Plant Paradox by Steven R. Gundry",
    "The 4-Hour Body by Timothy Ferriss",
    "The Paleo Solution by Robb Wolf",
    "The Complete Mediterranean Cookbook by America's Test Kitchen",
    "The Whole30 Cookbook by Melissa Hartwig and Dallas Hartwig",
    "The Blue Zones Kitchen by Dan Buettner",
    "The Longevity Diet by Valter Longo",
    "The End of Dieting by Dr. Joel Fuhrman",
    "The Starch Solution by John A. McDougall",
    "The Engine 2 Diet by Rip Esselstyn",
    "The China Study Cookbook by LeAnne Campbell",
    "The 5-Ingredient Mediterranean Diet Cookbook by Toby Amidor",
    "The Plant-Based Diet for Beginners by Gabriel Miller",
    "The Vegan Starter Kit by Neal D. Barnard",
    "The Flexitarian Diet by Dawn Jackson Blatner",
    "The DASH Diet Action Plan by Marla Heller",
    "The South Beach Diet by Arthur Agatston",
    "The Atkins Diet by Robert C. Atkins",
    "The Zone Diet by Barry Sears",
    "The Blood Sugar Solution by Mark Hyman",
    "The Fat Flush Plan by Ann Louise Gittleman",
    "The Paleo Diet by Loren Cordain",
    "The Raw Food Detox Diet by Natalia Rose",
    "The Engine 2 Seven-Day Rescue Diet by Rip Esselstyn",
    "The Whole30 Day by Day by Melissa Hartwig",
    "The Mediterranean Diet for Beginners by Rockridge Press",
    "The Plant Paradox Cookbook by Steven R. Gundry",
    "The 4-Hour Chef by Timothy Ferriss",
    "The Paleo Diet Cookbook by Loren Cordain",
    "The Blue Zones Solution Cookbook by Dan Buettner",
    "The Longevity Diet Cookbook by Valter Longo",
    "The End of Dieting Cookbook by Dr. Joel Fuhrman",
    "The Starch Solution Cookbook by John A. McDougall",
    "The Engine 2 Diet Cookbook by Rip Esselstyn",
    "The China Study Cookbook by LeAnne Campbell",
    "The 5-Ingredient Mediterranean Diet Cookbook by Toby Amidor",
    "The Plant-Based Diet for Beginners Cookbook by Gabriel Miller",
    "The Vegan Starter Kit Cookbook by Neal D. Barnard",
    "The Flexitarian Diet Cookbook by Dawn Jackson Blatner",
    "The DASH Diet Action Plan Cookbook by Marla Heller",
    "The South Beach Diet Cookbook by Arthur Agatston",
    "The Atkins Diet Cookbook by Robert C. Atkins",
    "The Zone Diet Cookbook by Barry Sears",
    "The Blood Sugar Solution Cookbook by Mark Hyman",
    "The Fat Flush Plan Cookbook by Ann Louise Gittleman",
    "The Paleo Diet Cookbook by Loren Cordain",
    "The Raw Food Detox Diet Cookbook by Natalia Rose"
  ],
  Spirituality : [
    "The Power of Now by Eckhart Tolle",
    "A New Earth by Eckhart Tolle",
    "The Untethered Soul by Michael A. Singer",
    "The Four Agreements by Don Miguel Ruiz",
    "The Seat of the Soul by Gary Zukav",
    "The Celestine Prophecy by James Redfield",
    "The Alchemist by Paulo Coelho",
    "The Secret by Rhonda Byrne",
    "The Seven Spiritual Laws of Success by Deepak Chopra",
    "The Book of Awakening by Mark Nepo",
    "The Power of Intention by Wayne Dyer",
    "The Art of Happiness by Dalai Lama XIV and Howard C. Cutler",
    "The Art of Communicating by Thich Nhat Hanh",
    "The Power of Positive Thinking by Norman Vincent Peale",
    "The Road Less Traveled by M. Scott Peck",
    "The Power of Vulnerability by Brené Brown",
    "The Wisdom of Sundays by Oprah Winfrey",
    "The Universe Has Your Back by Gabrielle Bernstein",
    "The Vortex by Esther Hicks and Jerry Hicks",
    "Ask and It Is Given by Esther Hicks and Jerry Hicks",
    "The Spontaneous Fulfillment of Desire by Deepak Chopra",
    "The Art of Living by Thich Nhat Hanh",
    "Meditations by Marcus Aurelius",
    "The Daily Stoic by Ryan Holiday",
    "Ego Is the Enemy by Ryan Holiday",
    "The Obstacle Is the Way by Ryan Holiday",
    "Stillness Is the Key by Ryan Holiday",
    "Indistractable by Nir Eyal",
    "Can't Hurt Me by David Goggins",
    "Unshakeable by Tony Robbins",
    "Money: Master the Game by Tony Robbins",
    "The Path Made Clear by Oprah Winfrey",
    "The Wisdom of Sundays by Oprah Winfrey",
    "What I Know for Sure by Oprah Winfrey",
    "The Year of Magical Thinking by Joan Didion",
    "Wild by Cheryl Strayed"],
  Relationships : [
    "The 5 Love Languages by Gary Chapman",
    "Attached by Amir Levine and Rachel S.F. Heller",
    "Hold Me Tight by Dr. Sue Johnson",
    "Men Are from Mars, Women Are from Venus by John Gray",
    "The Seven Principles for Making Marriage Work by John M. Gottman and Nan Silver",
    "The Relationship Cure by John M. Gottman and Joan DeClaire",
    "Getting the Love You Want by Harville Hendrix",
    "The Four Agreements by Don Miguel Ruiz",
    "Love Sense by Dr. Sue Johnson",
    "Mating in Captivity by Esther Perel",
    "The Five Love Languages of Children by Gary Chapman and Ross Campbell",
    "The Art of Loving by Erich Fromm",
    "The Mastery of Love by Don Miguel Ruiz",
    "Hold Me Tight by Dr. Sue Johnson",
    "Attached by Amir Levine and Rachel S.F. Heller",
    "The Seven Principles for Making Marriage Work by John M. Gottman and Nan Silver",
    "The Relationship Cure by John M. Gottman and Joan DeClaire",
    "Getting the Love You Want by Harville Hendrix",
    "The Four Agreements by Don Miguel Ruiz",
    "Love Sense by Dr. Sue Johnson",
    "Mating in Captivity by Esther Perel",
    "The Five Love Languages of Children by Gary Chapman and Ross Campbell",
    "The Art of Loving by Erich Fromm",
    "The Mastery of Love by Don Miguel Ruiz",
    "Hold Me Tight by Dr. Sue Johnson",
    "Attached by Amir Levine and Rachel S.F. Heller",
    "The Seven Principles for Making Marriage Work by John M. Gottman and Nan Silver",
    "The Relationship Cure by John M. Gottman and Joan DeClaire",
    "Getting the Love You Want by Harville Hendrix",
    "The Four Agreements by Don Miguel Ruiz",
    "Love Sense by Dr. Sue Johnson",
    "Mating in Captivity by Esther Perel",
    "The Five Love Languages of Children by Gary Chapman and Ross Campbell",
    "The Art of Loving by Erich Fromm",
    "The Mastery of Love by Don Miguel Ruiz",
    "Hold Me Tight by Dr. Sue Johnson",
    "Attached by Amir Levine and Rachel S.F. Heller",
    "The Seven Principles for Making Marriage Work by John M. Gottman and Nan Silver",
    "The Relationship Cure by John M. Gottman and Joan DeClaire",
    "Getting the Love You Want by Harville Hendrix",
    "The Four Agreements by Don Miguel Ruiz",
    "Love Sense by Dr. Sue Johnson",
    "Mating in Captivity by Esther Perel",
    "The Five Love Languages of Children by Gary Chapman and Ross Campbell",
    "The Art of Loving by Erich Fromm",
    "The Mastery of Love by Don Miguel Ruiz",
    "Hold Me Tight by Dr. Sue Johnson",
    "Attached by Amir Levine and Rachel S.F. Heller",
    "The Seven Principles for Making Marriage Work by John M. Gottman and Nan Silver",
    "The Relationship Cure by John M. Gottman and Joan DeClaire",
    "Getting the Love You Want by Harville Hendrix",
    "The Four Agreements by Don Miguel Ruiz",
    "Love Sense by Dr. Sue Johnson",
    "Mating in Captivity by Esther Perel",
    "The Five Love Languages of Children by Gary Chapman and Ross Campbell",
    "The Art of Loving by Erich Fromm",
    "The Mastery of Love by Don Miguel Ruiz"
  ],
  finance: [
    "Rich Dad Poor Dad by Robert T. Kiyosaki",
    "The Intelligent Investor by Benjamin Graham",
    "Think and Grow Rich by Napoleon Hill",
    "The Millionaire Next Door by Thomas J. Stanley and William D. Danko",
    "The Richest Man in Babylon by George S. Clason",
    "Your Money or Your Life by Vicki Robin and Joe Dominguez",
    "The Total Money Makeover by Dave Ramsey",
    "The Little Book of Common Sense Investing by John C. Bogle",
    "The Simple Path to Wealth by JL Collins",
    "The Psychology of Money by Morgan Housel",
    "The Barefoot Investor by Scott Pape",
    "The Automatic Millionaire by David Bach",
    "Financial Freedom by Grant Sabatier",
    "The Millionaire Fastlane by MJ DeMarco",
    "The Science of Getting Rich by Wallace D. Wattles",
    "The 4-Hour Workweek by Timothy Ferriss",
    "The Wealthy Gardener by John Soforic",
    "The Little Book of Riches by Michael LeBoeuf",
    "The Money Book for the Young, Fabulous & Broke by Suze Orman",
    "The Financial Diet by Chelsea Fagan and Lauren Ver Hage",
    "The Simple Dollar by Trent Hamm",
    "The Little Book of Wealth by Jason Butler",
    "The Money Master by Tony Robbins",
    "The Millionaire Mind by Thomas J. Stanley",
    "The Wealthy Gardener by John Soforic",
    "The Intelligent Investor by Benjamin Graham",
    "The Compound Effect by Darren Hardy",
    "The Cashflow Quadrant by Robert T. Kiyosaki",
    "The Wealthy Gardener by John Soforic",
    "The Little Book of Investing by John C. Bogle",
    "Smart Women Finish Rich by David Bach",
    "I Will Teach You to Be Rich by Ramit Sethi",
    "You Are a Badass at Making Money by Jen Sincero",
    "Principles: Life and Work by Ray Dalio",
    "The Millionaire Next Door by Thomas J. Stanley",
    "The Wealthy Gardener by John Soforic",
    "How to Build Wealth by James E. Smith",
    "The Personal MBA by Josh Kaufman",
    "The Millionaire Booklet by Grant Cardone",
    "The Secrets of the Millionaire Mind by T. Harv Eker",
    "Unshakeable by Tony Robbins",
    "The Power of Passive Income by Nightingale-Conant",
    "Money: Master the Game by Tony Robbins",
    "The Real Estate Investor's Handbook by Steven D. Fisher",
    "Financial Freedom by Grant Sabatier",
    "Wealth Can't Wait by David Osborn",
    "The Wealthy Gardener by John Soforic",
    "Live Rich by Catherine Alford",
    "Rich Dad's Guide to Investing by Robert T. Kiyosaki",
    "The Financial Freedom Formula by Grant Sabatier",
    "Early Retirement Extreme by Jacob Lund Fisker",
    "The Millionaire Next Door by Thomas Stanley",
    "You Are a Badass at Making Money by Jen Sincero"
  ]

}




export default Books;